volumes:
  frontend_built:
  caddy_data:
  caddy_config:
  backend_static:

services:
  backend:
    volumes:
      - backend_static:/opt/static
  frontend:
    command: sh -c "bun install && bun run build --outDir /tmp/dist && rm -rf /opt/dist/* && mv /tmp/dist /opt/dist"
    volumes:
      - frontend_built:/opt/dist

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - frontend_built:/opt/frontend/:ro
      - backend_static:/opt/static/:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    depends_on:
      - backend
