volumes:
  postgres_data:

services:
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
      - ./data/:/data/

  frontend:
    build: ./frontend
    depends_on:
      - backend

  memcached:
    image: memcached:latest

  db:
    build: ./services/postgres/
    env_file:
      - .env
    environment:
      # if 1 uses the postgresql_load.conf pg config, which is optimized for bulk loading,
      # but isn't safe for regular serving due to disabling crash recovery options
      - PGCONFIG_LOADING=0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/postgres/configs/postgresql_load.conf:/tmp/postgresql.conf # copied into data on server boot
      - ./db-exports/:/db-exports/
      - ./services/postgres/scripts/:/opt/scripts/
      - ./data/:/data/
    healthcheck:
      test: ["CMD-SHELL", "/opt/healthcheck.sh || exit 1"]
      interval: 5s
      timeout: 120s
      retries: 30
      start_period: 2m
